spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth, /
        - id: config
          uri: lb://CONFIG
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config, /

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
  endpoint:
    gateway:
      enabled: true
