#server:
#  ssl:
#    key-store: classpath:ws-keystore.p12
#    key-store-type: PKCS12
#    key-store-password: dnjstjr123
#    key-alias: ws-keystore

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*),/$\{path}
	- id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/oauth2/**
        - id: config-service
          uri: lb://CONFIG-SERVICE
          predicates:
            - Path=/config-service/**
          filters:
            - RewritePath=/config-service/(?<segment>.*),/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh
  endpoint:
    gateway:
      enabled: true
