server:
  ssl:
    key-store: classpath:ws-keystore.p12
    key-store-type: PKCS12
    key-store-password: dnjstjr123
    key-alias: ws-keystore

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth, /
        - id: config
          uri: lb://CONFIG
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config, /

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh
  endpoint:
    gateway:
      enabled: true
