spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
            - RewritePath=/auth-service, /
        - id: config-service
          uri: lb://CONFIG-SERVICE
          predicates:
            - Path=/config-service/**
  rabbitmq:
   host: localhost
   port: 5672
   stream:
     name: apigateway
     username: guest
     password: guest

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
  endpoint:
    gateway:
      enabled: true
