server:
  port: 41001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: order-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/orderdb
   #url: jdbc:h2:~/orderdb
    username: sa
  sql:
    init:
      mode: always
      data-locations: ''
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update #create #create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect